### ISSUE TITLE
 depends on integration_test any from sdk which doesn't exist

### ISSUE THREAD

**Issue by SogoGolf** [abuanwar072/Flutter-responsive-email-ui---Mobile-Tablet-and-Web#2]
thanks for the great looking example app. getting this error when trying to run ```flutter pub get```

Because outlook depends on integration_test any from sdk which doesn't exist (could not find package integration_test in the Flutter SDK), version solving failed.

id suggest just adding a reminder note on the README that devs needs to be on the flutter beta(?) channel

**Comment by NicoDevCode** [comment]
I have the same problem, 

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because outlook depends on integration_test any from sdk which doesn't exist (could not find package integration_test in the Flutter SDK), version solving failed

**Comment by NicoDevCode** [comment]
I have the same problem,

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because outlook depends on integration_test any from sdk which doesn't exist (could not find package integration_test in the Flutter SDK), version solving failed

**Comment by khalludi** [comment]
I was able to fix this issue by changing the `pubspec.yaml` file. I commented out the following lines around line 40:
```
# integration_test:
#    sdk: flutter
```

Instead, I add `integration_test: ^1.0.2+2` after the line containing `flutter_staggered_grid_view` on line 35. I think it could also be put under `dev_dependencies`, but I'm not sure since I'm still a beginner and still learning :)

Since I'm using the stable channel of Flutter, I also had to change the version number of `cupertino_icons` from `^1.0.1` to `^1.0.0`. After that everything ran!

**Comment by NerdFaisal404** [comment]
Please switch your flutter sdk channel branch from stable to beta . Because flutter integration_test is not available in stable channel.

**Comment by Ihsankapahi** [comment]
No idea about this subject

**Comment by ilyaas19** [comment]
Didn't get it bro

**Comment by abuanwar072** [comment]
check this
https://flutter.dev/docs/get-started/web
